#!/usr/bin/env bash

# MIT License

# Copyright (c) 2021 Andrei Datcu

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# See documentation about clitube here: https://github.com/datcuandrei/clitube

# introduction
clear
echo "️clitube"
echo "terminal-based YT streaming."
echo "----------------------------"
# getting the search query
echo "Search privately, using Invidious:"
read searchQuery

# temporarily downloading the search results
curl -s "https://ytprivate.com/api/v1/search?q=$(echo $searchQuery | tr " " +),type=video&pretty=1" --output /tmp/srch.json # using the -s to make curl dead silent;
																									 # tr is used to replace spaces with '+'

# getting all results and displaying them
clear
echo "Search Results"
echo "--------------"
grep -e "title" /tmp/srch.json | cut -b 14- | grep -n "," # displaying all results; piping '-n' to count the lines.

# getting the user requested video
echo ""
echo "Choose video [1-$(grep -e "title" /tmp/srch.json | wc --lines )]" # piping wc to get the number of lines.
read vid # variable that holds the index of the video

selectedVideo=$(grep -e "title" /tmp/srch.json | cut -b 14- | awk "NR==$vid{print;exit}") # the title of the selected video.
echo ""
videoId=$(grep -e "videoId" /tmp/srch.json | cut -b 17- | cut -b -11 | awk "NR==$vid{print;exit}") # getting the video ID
views=$(grep -e "viewCount" /tmp/srch.json | cut -b 18- | awk "NR==$vid{print;exit}") # the number of the views.
author=$(grep -e "\"author\":" /tmp/srch.json | cut -b 14- | awk "NR==$vid{print;exit}") # the author of the selected video.

# basic details about the selected video.
echo "► Now playing : $selectedVideo"
echo "© Published by : $author"
echo "👁 Number of views : $views"

# playing the selected video
echo ""
mpv --no-terminal "https://ytprivate.com/watch?v=$videoId" # making mpv quiet
echo ""
rm /tmp/srch.json # deleting the json file that contains the search results.
